"""add correct_choice_id

Revision ID: 454e682618e4
Revises: d04ff0d2b910
Create Date: 2023-07-18 01:38:57.644310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454e682618e4'
down_revision = 'd04ff0d2b910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_choice_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('correct_choice_id')

    # ### end Alembic commands ###
