"""change nullable

Revision ID: beda428316a5
Revises: 8c18fd87178f
Create Date: 2023-07-24 02:14:45.406167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'beda428316a5'
down_revision = '8c18fd87178f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_choice_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_choice_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
